### PR TITLE
[NET-0078] Implement Login Page

### LINKED ISSUE #78: NET-0078: Implement Login Page
**DoD**
- [ ] Initially opening app should lead to Login Page
- [ ] Should display errors from validation and/or authorization
- [ ] When login is successful, should redirect to app (blank 'landing page')

**Design Guide**
- [Figma Login Page Design](https://www.figma.com/file/BiANw7dW9baU65f2Nafsbs/?node-id=2%3A3)
- #86

**API**
- #8

**Relevant Story**
- As a user, I want to be able to log in, to use the app.
- As a product owner, I want to only allow legitimate registered users to use the app, for security and privacy reasons.

### PR DESCRIPTION
**Pull request by gachagas**
- Implemented login visuals
- There is validation on the inputs but no regex or anything. It just checks if the input contains anything at all. I could add regex stuff though.
- Routes to super bare page upon login
- 

I haven't implemented the authentication yet homie

Prerequisite: PR #95

### CODE REVIEW

**Comment by gachagas** [comment]
image

**Comment by gachagas** [comment]
https://www.elvisduru.com/blog/how-to-customize-ant-design-theme-in-nextjs 

you can change theme with these but i kinda dont want to push this because the compilation time increases a lot

**Review by RayAdrian — APPROVED** [review]
lgtm! 💯 🚀

**Review by themoeboy — APPROVED** [review]
looks good, please settle the Tailwind CSS package PR first.

**Pull request closed without merging**
