### PR TITLE
[NET-0092] Initialize AntDesign

### LINKED ISSUE #92: NET-0092: Setup Ant Design and other FE modules
**DoD**
- [x] Ant Design React library imported and usable
- [x] TailwindCSS
- [ ] Emotion

**Relevant Links**
- [Ant Design React](https://ant.design/docs/react/introduce)

**Relevant Story**
- As a developer, I want to reusable components, to streamline development of pages.

### PR DESCRIPTION
**Pull request by gachagas**
## Description
Install antd and add one of their sample form components

### CODE REVIEW

**Comment by gachagas** [comment]
image

**Review by allendomingo — APPROVED** [review]
Looks good to me! 🚀 🌔

**Review by RayAdrian — APPROVED** [review]
Lgtm. Next time please branch out from dev to a new branch using the ticket as branch name. This avoids merge conflicts in dev on your forked repo. 🚀

**Comment by allendomingo** [comment]
> Lgtm. Next time please branch out from dev to a new branch using the ticket as branch name. This avoids merge conflicts in dev on your forked repo. 🚀

+1

**Pull request merged**
